// Per-country metadata. This is what frontend devs actually need to build
// dynamic checkout forms: "which fields do I show for Germany vs Japan?",
// "what's a valid Dutch postcode regex?", etc.

export interface CountryMetadata {
  code: string;
  name: string;
  required_fields: string[];
  optional_fields: string[];
  postal_code_regex: string | null;
  postal_code_example: string;
  state_region_label: string | null;
  state_region_note: string | null;
  example_input: Record<string, string>;
}

// The base set every formatter expects
const BASE_REQUIRED = ['recipient', 'street', 'house_number', 'postal_code', 'city', 'country'];
const BASE_OPTIONAL = ['company', 'apartment', 'source_country'];

export const countryMetadata: Record<string, CountryMetadata> = {
  // --- EUROPE ---

  NL: {
    code: 'NL',
    name: 'Netherlands',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{4}\\s?[A-Za-z]{2}$',
    postal_code_example: '1012 LG',
    state_region_label: null,
    state_region_note: null,
    example_input: {
      recipient: 'Jan de Vries',
      street: 'Damrak',
      house_number: '70',
      postal_code: '1012LG',
      city: 'Amsterdam',
      country: 'NL',
    },
  },

  BE: {
    code: 'BE',
    name: 'Belgium',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{4}$',
    postal_code_example: '1000',
    state_region_label: null,
    state_region_note: null,
    example_input: {
      recipient: 'Marie Dubois',
      street: 'Rue de la Loi',
      house_number: '16',
      postal_code: '1000',
      city: 'Brussels',
      country: 'BE',
    },
  },

  LU: {
    code: 'LU',
    name: 'Luxembourg',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^(L-?)?\\d{4}$',
    postal_code_example: 'L-1234',
    state_region_label: null,
    state_region_note: null,
    example_input: {
      recipient: 'Pierre Weber',
      street: 'Avenue de la Liberté',
      house_number: '19',
      postal_code: '1931',
      city: 'Luxembourg',
      country: 'LU',
    },
  },

  DE: {
    code: 'DE',
    name: 'Germany',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{5}$',
    postal_code_example: '10115',
    state_region_label: null,
    state_region_note: null,
    example_input: {
      recipient: 'Hans Müller',
      street: 'Unter den Linden',
      house_number: '77',
      postal_code: '10117',
      city: 'Berlin',
      country: 'DE',
    },
  },

  AT: {
    code: 'AT',
    name: 'Austria',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{4}$',
    postal_code_example: '1010',
    state_region_label: null,
    state_region_note: null,
    example_input: {
      recipient: 'Anna Huber',
      street: 'Stephansplatz',
      house_number: '3',
      postal_code: '1010',
      city: 'Wien',
      country: 'AT',
    },
  },

  CH: {
    code: 'CH',
    name: 'Switzerland',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{4}$',
    postal_code_example: '8001',
    state_region_label: null,
    state_region_note: null,
    example_input: {
      recipient: 'Lukas Meier',
      street: 'Bahnhofstrasse',
      house_number: '42',
      postal_code: '8001',
      city: 'Zürich',
      country: 'CH',
    },
  },

  FR: {
    code: 'FR',
    name: 'France',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{5}$',
    postal_code_example: '75001',
    state_region_label: null,
    state_region_note: 'City is ALWAYS uppercase per La Poste, even domestic.',
    example_input: {
      recipient: 'Sophie Martin',
      street: 'Rue de Rivoli',
      house_number: '55',
      postal_code: '75001',
      city: 'Paris',
      country: 'FR',
    },
  },

  MC: {
    code: 'MC',
    name: 'Monaco',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^980\\d{2}$',
    postal_code_example: '98000',
    state_region_label: null,
    state_region_note: null,
    example_input: {
      recipient: 'Jean Dupont',
      street: 'Boulevard des Moulins',
      house_number: '17',
      postal_code: '98000',
      city: 'Monaco',
      country: 'MC',
    },
  },

  UK: {
    code: 'UK',
    name: 'United Kingdom',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^[A-Za-z]{1,2}\\d[A-Za-z\\d]?\\s?\\d[A-Za-z]{2}$',
    postal_code_example: 'SW1A 2AA',
    state_region_label: null,
    state_region_note: 'Town is ALWAYS uppercase per Royal Mail.',
    example_input: {
      recipient: 'Mr James Brown',
      street: 'Downing Street',
      house_number: '10',
      postal_code: 'SW1A 2AA',
      city: 'London',
      country: 'UK',
    },
  },

  GB: {
    code: 'GB',
    name: 'United Kingdom',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^[A-Za-z]{1,2}\\d[A-Za-z\\d]?\\s?\\d[A-Za-z]{2}$',
    postal_code_example: 'SW1A 2AA',
    state_region_label: null,
    state_region_note: 'Alias of UK. Town uppercase per Royal Mail.',
    example_input: {
      recipient: 'Mr James Brown',
      street: 'Downing Street',
      house_number: '10',
      postal_code: 'SW1A 2AA',
      city: 'London',
      country: 'GB',
    },
  },

  IE: {
    code: 'IE',
    name: 'Ireland',
    required_fields: BASE_REQUIRED,
    optional_fields: [...BASE_OPTIONAL, 'state_region'],
    postal_code_regex: '^[A-Za-z0-9]{3}\\s?[A-Za-z0-9]{4}$',
    postal_code_example: 'D02 X285',
    state_region_label: 'County',
    state_region_note: 'Optional county line between town and Eircode.',
    example_input: {
      recipient: 'John Murphy',
      street: 'Main Street',
      house_number: '123',
      postal_code: 'D02X285',
      city: 'Dublin 2',
      country: 'IE',
    },
  },

  IT: {
    code: 'IT',
    name: 'Italy',
    required_fields: BASE_REQUIRED,
    optional_fields: [...BASE_OPTIONAL, 'state_region'],
    postal_code_regex: '^\\d{5}$',
    postal_code_example: '00184',
    state_region_label: 'Province sigla',
    state_region_note: '2-letter province code (RM, MI, TO). Shown on domestic labels, dropped for international.',
    example_input: {
      recipient: 'Mario Rossi',
      street: 'Via Roma',
      house_number: '12',
      postal_code: '00184',
      city: 'Roma',
      state_region: 'RM',
      country: 'IT',
    },
  },

  ES: {
    code: 'ES',
    name: 'Spain',
    required_fields: BASE_REQUIRED,
    optional_fields: [...BASE_OPTIONAL, 'state_region'],
    postal_code_regex: '^\\d{5}$',
    postal_code_example: '28001',
    state_region_label: 'Provincia',
    state_region_note: 'Optional province name on own line if different from city.',
    example_input: {
      recipient: 'Pedro López',
      street: 'Calle Sevilla',
      house_number: '5',
      postal_code: '41001',
      city: 'Sevilla',
      state_region: 'Andalucía',
      country: 'ES',
    },
  },

  PT: {
    code: 'PT',
    name: 'Portugal',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{4}-?\\d{3}$',
    postal_code_example: '1100-053',
    state_region_label: null,
    state_region_note: null,
    example_input: {
      recipient: 'João Silva',
      street: 'Rua Augusta',
      house_number: '100',
      postal_code: '1100-053',
      city: 'Lisboa',
      country: 'PT',
    },
  },

  GR: {
    code: 'GR',
    name: 'Greece',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{3}\\s?\\d{2}$',
    postal_code_example: '104 31',
    state_region_label: null,
    state_region_note: null,
    example_input: {
      recipient: 'Nikos Papadopoulos',
      street: 'Ermou',
      house_number: '12',
      postal_code: '10431',
      city: 'Athens',
      country: 'GR',
    },
  },

  PL: {
    code: 'PL',
    name: 'Poland',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{2}-?\\d{3}$',
    postal_code_example: '00-001',
    state_region_label: null,
    state_region_note: 'Street auto-prefixed with "ul." if not already present.',
    example_input: {
      recipient: 'Anna Kowalska',
      street: 'Marszałkowska',
      house_number: '100',
      postal_code: '00-001',
      city: 'Warszawa',
      country: 'PL',
    },
  },

  CZ: {
    code: 'CZ',
    name: 'Czechia',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{3}\\s?\\d{2}$',
    postal_code_example: '120 00',
    state_region_label: null,
    state_region_note: null,
    example_input: {
      recipient: 'Jan Novák',
      street: 'Václavské náměstí',
      house_number: '1',
      postal_code: '11000',
      city: 'Praha',
      country: 'CZ',
    },
  },

  HU: {
    code: 'HU',
    name: 'Hungary',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{4}$',
    postal_code_example: '1051',
    state_region_label: null,
    state_region_note: 'Unusual order: city is above street, postcode is last. Hungarian name order typically puts family name first.',
    example_input: {
      recipient: 'Nagy Péter',
      street: 'Kossuth Lajos utca',
      house_number: '10',
      postal_code: '1051',
      city: 'Budapest',
      country: 'HU',
    },
  },

  SE: {
    code: 'SE',
    name: 'Sweden',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^(SE-?)?\\d{3}\\s?\\d{2}$',
    postal_code_example: '114 51',
    state_region_label: null,
    state_region_note: 'Domestic: "NNN NN". International: "SE-NNNNN".',
    example_input: {
      recipient: 'Erik Andersson',
      street: 'Drottninggatan',
      house_number: '1',
      postal_code: '11451',
      city: 'Stockholm',
      country: 'SE',
    },
  },

  DK: {
    code: 'DK',
    name: 'Denmark',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^(DK-?)?\\d{4}$',
    postal_code_example: '1050',
    state_region_label: null,
    state_region_note: '"DK-" prefix added for international mail.',
    example_input: {
      recipient: 'Anders Jensen',
      street: 'Strøget',
      house_number: '12',
      postal_code: '1050',
      city: 'København',
      country: 'DK',
    },
  },

  NO: {
    code: 'NO',
    name: 'Norway',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^(NO-?)?\\d{4}$',
    postal_code_example: '0150',
    state_region_label: null,
    state_region_note: '"NO-" prefix added for international mail.',
    example_input: {
      recipient: 'Ola Nordmann',
      street: 'Karl Johans gate',
      house_number: '1',
      postal_code: '0154',
      city: 'Oslo',
      country: 'NO',
    },
  },

  FI: {
    code: 'FI',
    name: 'Finland',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^(FI-?)?\\d{5}$',
    postal_code_example: '00100',
    state_region_label: null,
    state_region_note: '"FI-" prefix added for international mail.',
    example_input: {
      recipient: 'Matti Virtanen',
      street: 'Mannerheimintie',
      house_number: '1',
      postal_code: '00100',
      city: 'Helsinki',
      country: 'FI',
    },
  },

  // --- AMERICAS ---

  US: {
    code: 'US',
    name: 'United States',
    required_fields: [...BASE_REQUIRED, 'state_region'],
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{5}(-\\d{4})?$',
    postal_code_example: '10001',
    state_region_label: 'State',
    state_region_note: '2-letter USPS state code required (CA, NY, TX, etc.).',
    example_input: {
      recipient: 'John Smith',
      street: 'Main Street',
      house_number: '350',
      postal_code: '10001',
      city: 'New York',
      state_region: 'NY',
      country: 'US',
    },
  },

  CA: {
    code: 'CA',
    name: 'Canada',
    required_fields: [...BASE_REQUIRED, 'state_region'],
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^[A-Za-z]\\d[A-Za-z]\\s?\\d[A-Za-z]\\d$',
    postal_code_example: 'K1A 0B1',
    state_region_label: 'Province',
    state_region_note: '2-letter province code required (ON, QC, BC, AB, etc.).',
    example_input: {
      recipient: 'Jane Tremblay',
      street: 'Queen Street',
      house_number: '200',
      postal_code: 'K1A0B1',
      city: 'Ottawa',
      state_region: 'ON',
      country: 'CA',
    },
  },

  BR: {
    code: 'BR',
    name: 'Brazil',
    required_fields: [...BASE_REQUIRED, 'state_region'],
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{5}-?\\d{3}$',
    postal_code_example: '01310-100',
    state_region_label: 'Estado',
    state_region_note: '2-letter state code required (SP, RJ, MG, etc.).',
    example_input: {
      recipient: 'Ana Silva',
      street: 'Avenida Paulista',
      house_number: '1578',
      postal_code: '01310-200',
      city: 'São Paulo',
      state_region: 'SP',
      country: 'BR',
    },
  },

  MX: {
    code: 'MX',
    name: 'Mexico',
    required_fields: [...BASE_REQUIRED, 'state_region'],
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{5}$',
    postal_code_example: '06000',
    state_region_label: 'Estado',
    state_region_note: 'State name or abbreviation required (CDMX, JAL, NL, etc.).',
    example_input: {
      recipient: 'Carlos Hernández',
      street: 'Avenida Reforma',
      house_number: '222',
      postal_code: '06600',
      city: 'Ciudad de México',
      state_region: 'CDMX',
      country: 'MX',
    },
  },

  // --- ASIA-PACIFIC ---

  AU: {
    code: 'AU',
    name: 'Australia',
    required_fields: [...BASE_REQUIRED, 'state_region'],
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{4}$',
    postal_code_example: '2000',
    state_region_label: 'State',
    state_region_note: '2-3 letter state code required (NSW, VIC, QLD, WA, SA, TAS, ACT, NT).',
    example_input: {
      recipient: 'Emma Wilson',
      street: 'George Street',
      house_number: '200',
      postal_code: '2000',
      city: 'Sydney',
      state_region: 'NSW',
      country: 'AU',
    },
  },

  NZ: {
    code: 'NZ',
    name: 'New Zealand',
    required_fields: BASE_REQUIRED,
    optional_fields: [...BASE_OPTIONAL, 'state_region'],
    postal_code_regex: '^\\d{4}$',
    postal_code_example: '6011',
    state_region_label: 'Suburb',
    state_region_note: 'Optional suburb line between street and city.',
    example_input: {
      recipient: 'Oliver Thompson',
      street: 'Lambton Quay',
      house_number: '100',
      postal_code: '6011',
      city: 'Wellington',
      state_region: 'Pipitea',
      country: 'NZ',
    },
  },

  JP: {
    code: 'JP',
    name: 'Japan',
    required_fields: [...BASE_REQUIRED, 'state_region'],
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^〒?\\d{3}-?\\d{4}$',
    postal_code_example: '100-0001',
    state_region_label: 'Prefecture',
    state_region_note: 'Prefecture name required (Tokyo, Osaka, Kyoto, etc.). Output is romanised Latin format suitable for international carriers.',
    example_input: {
      recipient: 'Yuki Tanaka',
      street: 'Chiyoda',
      house_number: '1-1',
      postal_code: '100-0001',
      city: 'Chiyoda-ku',
      state_region: 'Tokyo',
      country: 'JP',
    },
  },

  SG: {
    code: 'SG',
    name: 'Singapore',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{6}$',
    postal_code_example: '238823',
    state_region_label: null,
    state_region_note: 'Apartment field used as unit number with "#" prefix (e.g. "#12-34").',
    example_input: {
      recipient: 'Wei Ming Tan',
      street: 'Orchard Road',
      house_number: '2',
      postal_code: '238823',
      city: 'Singapore',
      country: 'SG',
    },
  },

  HK: {
    code: 'HK',
    name: 'Hong Kong',
    required_fields: BASE_REQUIRED,
    optional_fields: [...BASE_OPTIONAL, 'state_region'],
    postal_code_regex: null,
    postal_code_example: '(no postal code)',
    state_region_label: 'District',
    state_region_note: 'Hong Kong does not use postal codes — pass any placeholder. City field holds the region (Hong Kong Island / Kowloon / New Territories).',
    example_input: {
      recipient: 'Chan Tai Man',
      street: 'Queens Road Central',
      house_number: '1',
      apartment: '1001',
      postal_code: '000000',
      city: 'Hong Kong Island',
      state_region: 'Central',
      country: 'HK',
    },
  },

  IN: {
    code: 'IN',
    name: 'India',
    required_fields: [...BASE_REQUIRED, 'state_region'],
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{6}$',
    postal_code_example: '110001',
    state_region_label: 'State',
    state_region_note: 'Full state name required (Maharashtra, Delhi, Karnataka, etc.).',
    example_input: {
      recipient: 'Priya Sharma',
      street: 'Connaught Place',
      house_number: '15',
      postal_code: '110001',
      city: 'New Delhi',
      state_region: 'Delhi',
      country: 'IN',
    },
  },

  // --- MIDDLE EAST + AFRICA ---

  AE: {
    code: 'AE',
    name: 'United Arab Emirates',
    required_fields: ['recipient', 'street', 'house_number', 'city', 'country'],
    optional_fields: [...BASE_OPTIONAL, 'state_region', 'postal_code'],
    postal_code_regex: null,
    postal_code_example: '(no postal code)',
    state_region_label: 'Emirate',
    state_region_note: 'UAE does not use postal codes for most locations — field is optional. state_region holds the emirate (Dubai, Abu Dhabi, etc.).',
    example_input: {
      recipient: 'Ahmed Al Maktoum',
      street: 'Sheikh Zayed Road',
      house_number: '1',
      postal_code: '00000',
      city: 'Dubai',
      state_region: 'Dubai',
      country: 'AE',
    },
  },

  IL: {
    code: 'IL',
    name: 'Israel',
    required_fields: BASE_REQUIRED,
    optional_fields: BASE_OPTIONAL,
    postal_code_regex: '^\\d{7}$',
    postal_code_example: '6100000',
    state_region_label: null,
    state_region_note: '7-digit postal code (as of 2013 reform).',
    example_input: {
      recipient: 'David Cohen',
      street: 'Dizengoff',
      house_number: '50',
      postal_code: '6433222',
      city: 'Tel Aviv',
      country: 'IL',
    },
  },

  ZA: {
    code: 'ZA',
    name: 'South Africa',
    required_fields: BASE_REQUIRED,
    optional_fields: [...BASE_OPTIONAL, 'state_region'],
    postal_code_regex: '^\\d{4}$',
    postal_code_example: '8001',
    state_region_label: 'Suburb',
    state_region_note: 'Optional suburb line between street and city.',
    example_input: {
      recipient: 'Thandi Nkosi',
      street: 'Long Street',
      house_number: '100',
      postal_code: '8001',
      city: 'Cape Town',
      state_region: 'City Bowl',
      country: 'ZA',
    },
  },
};

export function getCountryMetadata(code: string): CountryMetadata | null {
  return countryMetadata[code.toUpperCase()] || null;
}

export function getAllCountryMetadata(): CountryMetadata[] {
  return Object.values(countryMetadata).sort((a, b) => a.code.localeCompare(b.code));
}
